# PROYECTO EBA
## Flujo Completo
1. EXPLORACIÓN PREELIMINAR (Formatos / errores a grosso modo)
    - Abrir los ficheros
    - Comprobar formatos de columnas y filas
        - Detectar errores

2. LIMPIEZA GENERAL
    - Formato de Columnas
    - Columnas innecesarias
    - Formato de valores
    - Duplicados

3. LIMPIEZA ESPECIFICA
    - Tipo de los datos
    - Valores únicos por columna (¿errores?)
    - Gestion de nulos

4. TRANSFORMACIONES
    - Unificación de dataframes (en caso de ser necesario)
    - Ceación de nuevas columnas (agrupaciones, calculos, etc)

5. EXPLORACIÓN EN PROFUNDIDAD
    - Análisis descriptivo
        - Métricas generales
        - Explorar relación entre variables
    > Primeros gráficos

6. ANÁLISIS
    - Generación de hipótesis
    - Comprobación de hipótesis
    - Crear informe detallado
        - Objetivo
        - Hipótesis
        - Resultados con datos
        - Conclusies

## EXPLORACIÓN PREELIMINAR

### Apertura de ficheros (conversión a dataframe)
En primer lugar necesitamos poder acceder a la información de los ficheros, que nos vienen dados en dos formatos diferentres, como fichero CSV y como EXCEL.

En primer lugar definimos una función para atomatizar la apertura de ficheros de cualquier de los tipos, por lo que debe ser capaz de:
- Identificar el tipo de ficher (excel o csv)
- Transformarlo a dataframe (usando pandas)

> La función se crea dentro de la carpeta **infraestructure** (infraestrutura), en el archivo **file_utils.py** (utilidades de ficheros).

Una vez creada la función podemos importarla como el resto de librerías:

In [1]:
# Importamos las librerías necesarias para abrir nuestros data_frames
import pandas as pa
from infraestructure.file_utils import file_to_dataframe

In [2]:
# Generamos los dataframes para empezar a explorarlos
df_bank = file_to_dataframe('bank-additional.csv')
df_bank.head(2)

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,...,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,...,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097

In [3]:
# Queremos ver todos los nombres de columnas de este dataframe
df_bank.columns

Index(['Unnamed: 0', 'age', 'job', 'marital', 'education', 'default',
       'housing', 'loan', 'contact', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y', 'date', 'latitude',
       'longitude', 'id_'],
      dtype='object')

In [4]:
df_customer_12 = file_to_dataframe("customer-details.xlsx", "2012")
df_customer_13 = file_to_dataframe("customer-details.xlsx", "2013")
df_customer_14 = file_to_dataframe("customer-details.xlsx", "2014")

Path: C:\Users\Usuario\OneDrive\Documentos\GitHub\DataProyect_EDA_Python\files\input\customer-details.xlsx
Path: C:\Users\Usuario\OneDrive\Documentos\GitHub\DataProyect_EDA_Python\files\input\customer-details.xlsx
Path: C:\Users\Usuario\OneDrive\Documentos\GitHub\DataProyect_EDA_Python\files\input\customer-details.xlsx

In [5]:
df_customer_12.head(2)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097

In [6]:
df_customer_13.head(2)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,82407,0,1,2013-10-07,29,ef81336c-e41a-46d0-8a30-5d4ac3b836be
1,1,24877,0,0,2013-04-21,32,50b224ac-84b4-42a7-aba9-3e1d1d620479

In [7]:
df_customer_14.head(2)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,168812,1,1,2014-06-10,27,4d6c811c-0f24-4a73-b374-2ebd1f80d46e
1,1,108615,2,1,2014-04-05,24,eef0f24f-cbdb-4c67-b371-09d7bc59695e

### Comprobar columnas y filas

#### Observaciones iniciales
- Los nombres de las columnas de los ficheros no tienen un formato unificado
- Todas tienen una columna "Unnamed: 0" que es el index --> innecesaria 

#### Pasos de limpieza iniciales (columnas)
- Unificar el formato de los nombres de las columnas:
    - Nombres en mayúsculas
    - Sin espacios antes o despues
    - Eliminar la columna "Unnamed: 0" 

> Creamos una función de limpieza general en domain/formatting_utils.py

In [8]:
# Importamos la función creada para usarla en nustros dataframes
from infraestructure.formatting_utils import column_names_formatting

In [9]:
# Creamos una lista de dataframes para trabajar con ellos de manera mas eficiente (sin tener que ir uno a uno)
dataframe_list = [df_bank, df_customer_12, df_customer_13, df_customer_14]

# Primero eliminamos de todos la columna que nos sobra "Unnamed: 0"
df_bank, df_customer_12, df_customer_13, df_customer_14 = map(lambda df: df.drop(columns=["Unnamed: 0"], errors="ignore"), dataframe_list)

# Actualizamos la lista de dataframes con la versión actualizada
dataframe_list = [df_bank, df_customer_12, df_customer_13, df_customer_14]

# Y pasamos nuestra función de limpieza de nombres
df_bank, df_customer_12, df_customer_13, df_customer_14 = map(column_names_formatting, dataframe_list)

Y comprobamos que nuestros cambios se han realizado correctamente:

In [10]:
# Imprimimos los nombres de las columnas para comprobar que en efecto se han formateado corretamente
for df in dataframe_list:
    print(df.columns)

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'duration', 'campaign', 'pdays', 'previous', 'poutcome',
       'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m',
       'nr.employed', 'y', 'date', 'latitude', 'longitude', 'id_'],
      dtype='object')
Index(['Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth',
       'ID'],
      dtype='object')
Index(['Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth',
       'ID'],
      dtype='object')
Index(['Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth',
       'ID'],
      dtype='object')

### Análisis inicial de cada dataframe
Una vez realizado el ajuste básico del formato de columnas pasamos a analizar con algo mas de detalle los aspectos básicos de cada uno de los dataframes.

Necesitamos explorar:
- Tipos de datos de cada columna
- Si hay duplicados
- Si hay nulos y en qué porcentaje para cada columna
- En las columnas categóricas:
    - Valores únicos existentes
        - Detectar posibles errores

#### Duplicados
Vamos a empezar por la gestion de valores duplicados que es la más sencilla porque tenemos un método específico para gestionarlos:
```
drop_duplicates()
```

In [11]:
# Volvemos a generar nuestra lista de dataframes
df_names = ["df_bank", "df_customer_12", "df_customer_13", "df_customer_14"]
dataframe_list = [df_bank, df_customer_12, df_customer_13, df_customer_14]

In [12]:
# Y contamos el numero de duplicados por dataframe
for (name, df) in zip(df_names, dataframe_list):
    print(f'{name} - {df.duplicated().sum()} duplicates')

df_bank - 0 duplicates
df_customer_12 - 0 duplicates
df_customer_13 - 0 duplicates
df_customer_14 - 0 duplicates

Como no tenemos duplicados, no es necesario hacer ningun paso adicional. Pero en caso de haberlos, bastaría con utilizar la siguiente línea de código:
```py
df_bank, df_customer_12, df_customer_13, df_customer_14 = map(lambda df: df.drop_duplicates(),dataframe_list)
```

#### Tipos de datos por df y columna
Necesitamos empezar a mirar con más detalle la organización interna de cada uno de los dataframes. Para tener una idea general de la cantidad de datos, tipo de dato de cada columna, numero de nulos, etc. contamos con el métido **info()**.

##### Análisis dataframe de campaña de márketing (df_bank)

In [13]:
df_bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   AGE           37880 non-null  float64
 1   JOB           42655 non-null  object
 2   MARITAL       42915 non-null  object
 3   EDUCATION     41193 non-null  object
 4   DEFAULT       34019 non-null  float64
 5   HOUSING       41974 non-null  float64
 6   LOAN          41974 non-null  float64
 7   CONTACT       43000 non-null  object
 8   DURATION      43000 non-null  int64
 9   CAMPAIGN      43000 non-null  int64
 10  PDAYS         43000 non-null  int64
 11  PREVIOUS      43000 non-null  int64
 12  POUTCOME      43000 non-null  object
 13  EMPVARRATE    43000 non-null  float64
 14  CONSPRICEIDX  42529 non-null  object
 15  CONSCONFIDX   43000 non-null  object
 16  EURIBOR3M     33744 non-null  object
 17  NREMPLOYED    43000 non-null  object
 18  Y             43000 non-null  object
 19  DATE          42752 non-null  object
 20  LATITUDE      43000 non-null  float64
 21  LONGITUDE     43000 non-null  float64
 22  ID            43000 non-null  object
dtypes: float64(7), int64(4), object(12)
memory usage: 7.5+ MB

El método **info()** nos da una idea general de que:
- Hay 43000 registros (filas) en total
- Hay columnas con valores nulos
- Reparto de tipos de columnas:
    - Decimales (float64): 7 columnas
    - Enteros (int54): 4 columnas
    - Categoricos (object): 12 columnas

Pero queremos mirar en mas detalle, por lo que vamos a crear funciones que nos permitan extraer información más a detalle:
- Porcentaje de nulos por columna
- Valores únicos dentro de las columnas categóricas

Este proceso, que nos servirá para la valoración de los demás dataframes tambien, nos será útil para decidir:
- Si alguna columna requiere un cambio de tipo de dato
- Si alguna columna categórica requiere de una limpieza personalziada (ej. valores con errores)
- Mejor manera de gestionar los valores nulos
- Valorar creación de nuevas columnas que aporten información complementaria

##### Función info extendida
En eda/infraestructure/explore_utils creamos una función llamada **info_dataframe** que nos dará información adicional sobre los datos del dataframe:

In [14]:
# Importamos el fichero con la funcion
from infraestructure.explore_utils import info_dataframe

In [16]:
df_info_bank = info_dataframe(df_bank)
df_info_bank

     COLUMN_NAME  NON_NULL_COUNT  NULL_COUNT  NULL_PERCENT    DTYPE
0            AGE           37880        5120         11.91  float64
1            JOB           42655         345          0.80   object
2        MARITAL           42915          85          0.20   object
3      EDUCATION           41193        1807          4.20   object
4        DEFAULT           34019        8981         20.89  float64
5        HOUSING           41974        1026          2.39  float64
6           LOAN           41974        1026          2.39  float64
7        CONTACT           43000           0          0.00   object
8       DURATION           43000           0          0.00    int64
9       CAMPAIGN           43000           0          0.00    int64
10         PDAYS           43000           0          0.00    int64
11      PREVIOUS           43000           0          0.00    int64
12      POUTCOME           43000           0          0.00   object
13    EMPVARRATE           43000           0          0.00  float64
14  CONSPRICEIDX           42529         471          1.10   object
15   CONSCONFIDX           43000           0          0.00   object
16     EURIBOR3M           33744        9256         21.53   object
17    NREMPLOYED           43000           0          0.00   object
18             Y           43000           0          0.00   object
19          DATE           42752         248          0.58   object
20      LATITUDE           43000           0          0.00  float64
21     LONGITUDE           43000           0          0.00  float64
22            ID           43000           0          0.00   object

In [22]:
for value,ty in zip(df_info_bank["COLUMN_NAME" ],df_info_bank["DTYPE" ]):
    print(f'{value} ---> {ty}')

AGE ---> float64
JOB ---> object
MARITAL ---> object
EDUCATION ---> object
DEFAULT ---> float64
HOUSING ---> float64
LOAN ---> float64
CONTACT ---> object
DURATION ---> int64
CAMPAIGN ---> int64
PDAYS ---> int64
PREVIOUS ---> int64
POUTCOME ---> object
EMPVARRATE ---> float64
CONSPRICEIDX ---> object
CONSCONFIDX ---> object
EURIBOR3M ---> object
NREMPLOYED ---> object
Y ---> object
DATE ---> object
LATITUDE ---> float64
LONGITUDE ---> float64
ID ---> object

In [25]:
df_info_bank.where(df_info_bank['DTYPE'] == "object")

     COLUMN_NAME  NON_NULL_COUNT  NULL_COUNT  NULL_PERCENT   DTYPE
0            NaN             NaN         NaN           NaN     NaN
1            JOB         42655.0       345.0          0.80  object
2        MARITAL         42915.0        85.0          0.20  object
3      EDUCATION         41193.0      1807.0          4.20  object
4            NaN             NaN         NaN           NaN     NaN
5            NaN             NaN         NaN           NaN     NaN
6            NaN             NaN         NaN           NaN     NaN
7        CONTACT         43000.0         0.0          0.00  object
8            NaN             NaN         NaN           NaN     NaN
9            NaN             NaN         NaN           NaN     NaN
10           NaN             NaN         NaN           NaN     NaN
11           NaN             NaN         NaN           NaN     NaN
12      POUTCOME         43000.0         0.0          0.00  object
13           NaN             NaN         NaN           NaN     NaN
14  CONSPRICEIDX         42529.0       471.0          1.10  object
15   CONSCONFIDX         43000.0         0.0          0.00  object
16     EURIBOR3M         33744.0      9256.0         21.53  object
17    NREMPLOYED         43000.0         0.0          0.00  object
18             Y         43000.0         0.0          0.00  object
19          DATE         42752.0       248.0          0.58  object
20           NaN             NaN         NaN           NaN     NaN
21           NaN             NaN         NaN           NaN     NaN
22            ID         43000.0         0.0          0.00  object

In [27]:
df_filtered = df_info_bank[df_info_bank["DTYPE"] == "object"]
df_filtered

     COLUMN_NAME  NON_NULL_COUNT  NULL_COUNT  NULL_PERCENT   DTYPE
1            JOB           42655         345          0.80  object
2        MARITAL           42915          85          0.20  object
3      EDUCATION           41193        1807          4.20  object
7        CONTACT           43000           0          0.00  object
12      POUTCOME           43000           0          0.00  object
14  CONSPRICEIDX           42529         471          1.10  object
15   CONSCONFIDX           43000           0          0.00  object
16     EURIBOR3M           33744        9256         21.53  object
17    NREMPLOYED           43000           0          0.00  object
18             Y           43000           0          0.00  object
19          DATE           42752         248          0.58  object
22            ID           43000           0          0.00  object